// xml.h
// XML Game Engine
// author: beefviper
// date: Sept 18, 2020

#pragma once

// disable warnings generated by tinyxml2
#pragma warning(push)
#pragma warning(disable : 26812)

#include <tinyxml2.h>

#pragma warning(pop)

#include <iostream>
#include <string>

namespace tx = tinyxml2;

namespace xge
{
	void checkXMLResult(tx::XMLDocument& xml, tx::XMLError result);
	tx::XMLElement* getXMLRoot(tx::XMLElement* element);
	tx::XMLElement* getXMLElement(tx::XMLElement* element, std::string tag);
	tx::XMLElement* getXMLElementOptional(tx::XMLElement* element, std::string tag);
	std::string getXMLText(tx::XMLElement* element);
	std::string getXMLAttribute(tx::XMLElement* element, std::string attribute);
	std::string getXMLAttributeOptional(tx::XMLElement* element, std::string attribute);
	int getXMLAttributeInt(tx::XMLElement* element, std::string attribute);
	float getXMLAttributeFloat(tx::XMLElement* element, std::string attribute);
}