// utils.h
// XML Game Engine
// author: beefviper
// date: Sept 18, 2020

#pragma once

// disable warnings generated by SFML
#pragma warning(disable : 26812)

#include <string>

#include <SFML/Graphics/Color.hpp>
#include <SFML/Window/Keyboard.hpp>

namespace xge
{
	struct Vector2str
	{
		std::string x;
		std::string y;
	};

	struct WindowDesc
	{
		std::string name;
		float width{};
		float height{};
		std::string background;
		std::string fullscreen;
		int framerate{};
	};
	
	sf::Color sfmlColor(std::string color);
	std::string sfmlKeyToString(sf::Keyboard::Key key);
}
